#!/usr/bin/env bash

PI_SKIP_VERSION_CHECK=1

docker run --rm -it \
  -u $(id -u):$(id -g) \
  -v "$HOME/.pi/pi-chrome/agent/":"/home/node/.pi/agent/" \
  -v "$HOME/.pi/pi-chrome/agent-downloads/":"/home/node/Downloads/" \
  -v "$HOME/.pi/pi-chrome/chrome-profile/":"/home/node/chrome-profile/" \
  -v "$PWD":"/workspace" \
  -w /workspace \
  -e PI_SKIP_VERSION_CHECK="$PI_SKIP_VERSION_CHECK" \
  -p 127.0.0.1:6080:6080 \
  --shm-size=2g \
  --security-opt seccomp=unconfined \
  pi-chromium:latest
