#!/usr/bin/env bash

PI_SKIP_VERSION_CHECK=1

mkdir -p \
    "$HOME/.pi/pi-chromium/agent" \
    "$HOME/.pi/pi-chromium/agent-downloads" \
    "$HOME/.pi/pi-chromium/chromium-profile"

docker run --rm -it \
  -u $(id -u):$(id -g) \
  -v "$HOME/.pi/pi-chromium/agent/":"/home/node/.pi/agent/" \
  -v "$HOME/.pi/pi-chromium/agent-downloads/":"/home/node/Downloads/" \
  -v "$HOME/.pi/pi-chromium/chromium-profile/":"/home/node/chromium-profile/" \
  -v "$PWD":"/workspace" \
  -w /workspace \
  -e PI_SKIP_VERSION_CHECK="$PI_SKIP_VERSION_CHECK" \
  -p 127.0.0.1:6080:6080 \
  --shm-size=2g \
  --security-opt seccomp=unconfined \
  pi-chromium:latest
